#!/home/santatra/projet_kely/py-env/rl-env/bin/python
import os

print("LIST ..........")
os.system('python lpma.py list')
os.system('python lpma.py list -s')
os.system('python lpma.py list -l')
print()

print("ADD ..........")
os.system("python lpma.py add --name testPojrect -c \"my comment\" -T \"my tech\" -T \"another tech\" -p //run//santatra")
print()

print("DESCRIBE ..........")
os.system('python lpma.py desc testpojrect')
print("REMOVE ..........")
os.system('python lpma.py rm testpojrect')

print("LIST ..........")
os.system('python lpma.py list -l')
print()
